/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventrypackage;

import db.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oshan Premachandra
 */
public class StokAddingHistory extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    /**
     * Creates new form StokAddingHistory
     */
    public StokAddingHistory() {
        initComponents();
        
        dtm = (DefaultTableModel) StockAddingTable.getModel();
        
        LoadStockHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StockAddingTable = new javax.swing.JTable();
        Home = new javax.swing.JButton();
        RemoveBtn = new javax.swing.JButton();
        pbid = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        pcode = new javax.swing.JLabel();
        stockai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1400, 900));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock Adding History");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        StockAddingTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        StockAddingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Code", "Quantity", "Cost Amount", "Product Add Date", "Price Batch Id", "Stock Adding History Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockAddingTable.setRowHeight(25);
        StockAddingTable.setSelectionBackground(new java.awt.Color(0, 51, 102));
        StockAddingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockAddingTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StockAddingTable);
        if (StockAddingTable.getColumnModel().getColumnCount() > 0) {
            StockAddingTable.getColumnModel().getColumn(5).setMinWidth(0);
            StockAddingTable.getColumnModel().getColumn(5).setPreferredWidth(0);
            StockAddingTable.getColumnModel().getColumn(5).setMaxWidth(0);
            StockAddingTable.getColumnModel().getColumn(6).setMinWidth(0);
            StockAddingTable.getColumnModel().getColumn(6).setPreferredWidth(0);
            StockAddingTable.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 51, 102));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        RemoveBtn.setBackground(new java.awt.Color(255, 255, 255));
        RemoveBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        RemoveBtn.setForeground(new java.awt.Color(255, 0, 51));
        RemoveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        RemoveBtn.setText("Remove");
        RemoveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveBtnMouseClicked(evt);
            }
        });

        pbid.setForeground(new java.awt.Color(255, 255, 255));

        qty.setForeground(new java.awt.Color(255, 255, 255));

        pcode.setForeground(new java.awt.Color(255, 255, 255));

        stockai.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Home)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stockai, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pcode, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pbid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(RemoveBtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home)
                            .addComponent(RemoveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoadStockHistory(){
        ResultSet SAH = Database.getData("SELECT * FROM STOCKADDINGHISTORY SAH INNER JOIN PRICEBATCH PB ON SAH.PRICEBATCHID=PB.ID INNER JOIN PRODUCTTBL PT ON PB.PRODCODE=PT.PRODCODE ");
        dtm.setRowCount(0);
        try {
            while(SAH.next()){

                Vector p = new Vector();
                p.add(SAH.getString(12));
                p.add(SAH.getString(7));
                p.add(SAH.getInt(4));
                p.add(SAH.getDouble(3));
                p.add(SAH.getString(5));
                p.add(SAH.getInt(2));
                p.add(SAH.getInt(1));

                dtm.addRow(p);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void StockAddingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockAddingTableMouseClicked
        
        String prcode = (String) StockAddingTable.getValueAt(StockAddingTable.getSelectedRow(), 1);
        int pqty = (int) StockAddingTable.getValueAt(StockAddingTable.getSelectedRow(), 2);
        int prbid = (int) StockAddingTable.getValueAt(StockAddingTable.getSelectedRow(), 5);
        int sahid = (int) StockAddingTable.getValueAt(StockAddingTable.getSelectedRow(), 6);
        
        qty.setText(pqty+"");
        pbid.setText(prbid+"");
        pcode.setText(prcode);
        stockai.setText(sahid+"");
         
    }//GEN-LAST:event_StockAddingTableMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void RemoveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveBtnMouseClicked
        
        if(pbid.getText().isEmpty() || pcode.getText().isEmpty() || qty.getText().isEmpty() || stockai.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Select data to be deleted.");
        }else{
            
            
            if(Database.saveData("DELETE FROM STOCKADDINGHISTORY WHERE ID = "+stockai.getText()+" ")){
                System.out.println("Only Stock History deleted successfully.");
                
                if(Database.saveData("UPDATE PRICEBATCH SET PRODQTY = PRODQTY - "+qty.getText()+" WHERE ID = "+pbid.getText()+" ")){
                    System.out.println("Only Update priceBatch deleted successfully.");
                
                    if(Database.saveData("UPDATE PRODUCTTBL SET PRODQTY = PRODQTY - "+qty.getText()+" WHERE PRODCODE='"+pcode.getText()+"'")){
                        JOptionPane.showMessageDialog(rootPane, "Stock deleted successfully.");
                        System.out.println("Stock deleted successfully.");
                        
                        LoadStockHistory();

                        qty.setText("");
                        pbid.setText("");
                        pcode.setText("");
                        stockai.setText("");
                        
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Failed, ERROR CODE: SPRITE");
                        System.out.println("Failed, ERROR CODE: SPRITE");
                    }    
                    
                
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Failed, ERROR CODE: COKE");
                    System.out.println("Failed, ERROR CODE: COKE");
                }
                
                
                
                
                
            }else{
                    JOptionPane.showMessageDialog(rootPane, "Failed, ERROR CODE: SNAKE");
                    System.out.println("Failed, ERROR CODE: SNAKE");
                }
            
        }
        
        
        
    }//GEN-LAST:event_RemoveBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokAddingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokAddingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokAddingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokAddingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokAddingHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JTable StockAddingTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pbid;
    private javax.swing.JLabel pcode;
    private javax.swing.JLabel qty;
    private javax.swing.JLabel stockai;
    // End of variables declaration//GEN-END:variables
}
